### PR TITLE
Add type annotations to `molplotly/main.py`

### PR DESCRIPTION
**Pull request by janosh**
You may want to add a GitHub action that runs  `mypy` on pushes and PRs to `main`.

### CODE REVIEW

**Comment by wjm41** [comment]
Good idea!  I'll have to look into how `mypy` works, will get back to you on that

**Comment by janosh** [comment]
I can help setup a GitHub action for linters if you like. The alternative would be https://pre-commit.ci.

**Comment by wjm41** [comment]
Sure thing! Whichever works best - from my understanding `pre-commit.ci` is more general/flexible right? All of this is quite new to me haha

**Comment by janosh** [comment]
GHA could be said to be more flexible since it allows you to run any shell script you like whereas pre-commit only runs git hooks. Of course those hooks could also be any shell script so it doesn't matter much in the end. pre-commit.ci has the advantage that it auto-formats PRs. Pushing to PRs from GHA is much more difficult.

**Comment by janosh** [comment]
I tend to prefer GHA for testing and pre-commit for linters like `mypy`.

**Comment by wjm41** [comment]
Thanks for helping @janosh! Finally merging this :P

**Pull request merged**
